name: Hello World
description: 'Greet someone'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Test temp.txt file content
      shell: bash
      run: cat temp.txt
    - name: Test temp.txt file content
      shell: bash
      run: echo "Hello World from hello-world action" > hello.txt
    - name: Set Greeting
      shell: bash
      run: echo "Hello $INPUT_WHO_TO_GREET."
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    - name: Random Number Generator
      shell: bash
      id: random-number-generator
      run: echo "random-number=2" >> $GITHUB_OUTPUT
